const $=id=>document.getElementById(id),c=$('game'),ctx=c.getContext('2d');let W,H,DPR,mode='menu',ws=null,room='',me='',mobile=localStorage.getItem('bm-mobile')==='1',last=performance.now(),keys=new Set(),joy={on:false,x:0,y:0},hero={x:420,y:360,speed:210,money:500,debt:1000000,level:1,xp:0,day:1,rep:0,burger:0,bun:0,patty:0,cheese:0,fries:0,orders:0,completed:0,upgrades:{grill:1,shop:1,seats:1,quality:1}},others=new Map(),saveSlots={};const station={grill:{x:650,y:250},bun:{x:650,y:430},assembly:{x:850,y:340},fryer:{x:1050,y:250},cash:{x:1050,y:470}},recipes=['Classic Burger','Cheese Burger','Double Burger','Fries Combo'];let order=recipes[0],orderStep=0,orderTimer=0;function resize(){W=innerWidth;H=innerHeight;DPR=Math.min(devicePixelRatio,2);c.width=W*DPR;c.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0)}addEventListener('resize',resize);resize();
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function ui(){ $('money').textContent=Math.floor(hero.money).toLocaleString('de-DE');$('debt').textContent=Math.max(0,Math.floor(hero.debt)).toLocaleString('de-DE');$('level').textContent=hero.level;$('room').textContent=room||'OFFLINE';$('order').innerHTML=`Bestellung: <b>${order}</b><small>${stepText()}</small>`;document.body.classList.toggle('mobileOn',mobile);$('mobileToggle').checked=mobile}
function stepText(){return ['Brötchen vorbereiten','Patty grillen','Burger zusammenbauen','Bestellung kassieren'][Math.min(orderStep,3)]}
function startGame(){mode='game';$('menu').classList.add('hidden');$('join').classList.add('hidden');$('hud').classList.remove('hidden');ui();newOrder();}
function newOrder(){order=recipes[Math.floor(Math.random()*recipes.length)];orderStep=0;orderTimer=35+Math.random()*20;ui()}
function connect(type,code){const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}`);ws.onopen=()=>ws.send(JSON.stringify({type,name:$('name').value||'Hero',code}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='roomCreated'||m.type==='joined'){room=m.code;me=m.id;startGame();toast(m.type==='roomCreated'?`Room ${room} erstellt`:'CO-OP verbunden')}if(m.type==='state'){room=m.code||room;for(const p of m.players||[]){if(p.id===me){hero.x=p.x;hero.y=p.y}else others.set(p.id,p)}}if(m.type==='error')toast(m.message)};ws.onclose=()=>toast('Server getrennt')}
$('create').onclick=()=>connect('create');$('joinOpen').onclick=()=>{$('menu').classList.add('hidden');$('join').classList.remove('hidden')};$('join').onclick=()=>connect('join',$('code').value.toUpperCase());$('back').onclick=()=>{$('join').classList.add('hidden');$('menu').classList.remove('hidden')};$('how').onclick=()=>$('storyPanel').classList.remove('hidden');$('storyClose').onclick=()=>$('storyPanel').classList.add('hidden');$('settings').onclick=()=>$('settingsPanel').classList.remove('hidden');$('settingsClose').onclick=()=>$('settingsPanel').classList.add('hidden');$('mobileToggle').onchange=e=>{mobile=e.target.checked;localStorage.setItem('bm-mobile',mobile?'1':'0');ui();toast(mobile?'Mobile Steuerung AN':'Mobile Steuerung AUS')};$('load').onclick=()=>$('savePanel').classList.remove('hidden');$('saveClose').onclick=()=>$('savePanel').classList.add('hidden');
function save(slot){const code=String(1000+Math.floor(Math.random()*9000));const data={...hero,saveCode:code,order,orderStep,worldVersion:'Burger Mafia V2.0 BETA'};localStorage.setItem('bm-slot-'+slot,JSON.stringify(data));localStorage.setItem('bm-code-'+code,JSON.stringify(data));$('saveCode').textContent=`SAVE-CODE: ${code}`;toast('GAME SAVED — Schicht '+hero.day)}function loadData(data){Object.assign(hero,data);order=data.order||recipes[0];orderStep=data.orderStep||0;startGame();toast('SAVE GELADEN — letzte Schicht');}
document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>save(b.dataset.slot));$('loadByCode').onclick=()=>{const code=$('loadCode').value.trim();let raw=null;for(let i=1;i<=3;i++){const x=localStorage.getItem('bm-slot-'+i);if(x&&JSON.parse(x).saveCode===code)raw=x}raw=raw||localStorage.getItem('bm-code-'+code);if(raw)loadData(JSON.parse(raw));else toast('Save-Code nicht gefunden')};
function near(s){return Math.hypot(hero.x-station[s].x,hero.y-station[s].y)<85}function interact(){if(near('bun')&&orderStep===0){hero.bun++;orderStep=1;toast('🍞 Brötchen vorbereitet')}else if(near('grill')&&orderStep===1){hero.patty++;orderStep=2;toast('🔥 Patty perfekt gegrillt')}else if(near('assembly')&&orderStep===2){hero.burger++;orderStep=3;toast('🍔 Burger fertig')}else if(near('cash')&&orderStep===3){const pay=45+hero.upgrades.quality*5;hero.money+=pay;hero.debt=Math.max(0,hero.debt-pay);hero.completed++;hero.xp+=25;toast(`💵 +€${pay} — Bestellung verkauft!`);if(hero.xp>=hero.level*100){hero.xp=0;hero.level++;hero.money+=100;toast('⭐ LEVEL UP!')}newOrder()}else if(near('fryer')){hero.fries++;toast('🍟 Pommes vorbereitet')}ui()}
function upgrade(){const prices={grill:500,shop:900,seats:1200,quality:700};const k=prompt('Upgrade: grill / shop / seats / quality');if(!prices[k])return;if(hero.money>=prices[k]){hero.money-=prices[k];hero.upgrades[k]++;toast(`🔧 ${k} verbessert`)}else toast('Nicht genug Geld');ui()}
addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='q')newOrder();if(e.key.toLowerCase()==='i')$('savePanel').classList.remove('hidden');if(e.key.toLowerCase()==='u')upgrade()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function send(){if(ws?.readyState===1)ws.send(JSON.stringify({type:'input',x:hero.x,y:hero.y,money:hero.money,level:hero.level,hp:100}))}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#24352c';ctx.fillRect(0,0,W,H);const sx=W/2-hero.x,sy=H/2-hero.y;ctx.save();ctx.translate(sx,sy);ctx.fillStyle='#33453a';ctx.fillRect(0,0,1500,900);for(let x=0;x<1500;x+=60){ctx.fillStyle=x%120?'#3b4e40':'#425846';ctx.fillRect(x,0,58,900)}ctx.fillStyle='#18201b';ctx.fillRect(500,120,700,560);ctx.fillStyle='#8c6b43';ctx.fillRect(540,160,620,480);for(const [k,p] of Object.entries(station)){ctx.fillStyle=k==='grill'?'#d15c36':k==='fryer'?'#e0a33a':k==='cash'?'#4ba06d':k==='assembly'?'#d6c06a':'#b88655';ctx.fillRect(p.x-45,p.y-35,90,70);ctx.fillStyle='#111';ctx.font='bold 14px system-ui';ctx.textAlign='center';ctx.fillText(k.toUpperCase(),p.x,p.y+5)}ctx.fillStyle='#f5b33b';ctx.beginPath();ctx.arc(hero.x,hero.y,24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText('YOU',hero.x,hero.y-32);for(const p of others.values()){ctx.fillStyle='#6ec8ff';ctx.beginPath();ctx.arc(p.x,p.y,24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(p.name||'COOP',p.x,p.y-32)}ctx.restore()}
function move(dt){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(joy.on){x=joy.x;y=joy.y}const l=Math.hypot(x,y)||1;hero.x+=x/l*hero.speed*dt;hero.y+=y/l*hero.speed*dt;hero.x=Math.max(160,Math.min(1320,hero.x));hero.y=Math.max(120,Math.min(760,hero.y))}
function loop(t){const dt=Math.min(.04,(t-last)/1000);last=t;if(mode==='game'){move(dt);orderTimer-=dt;if(orderTimer<=0){hero.money=Math.max(0,hero.money-15);toast('😡 Kunde gegangen — -€15');newOrder()}send();ui();draw()}requestAnimationFrame(loop)}requestAnimationFrame(loop);
let activeTouch=null;$('joy').addEventListener('pointerdown',e=>{activeTouch=e.pointerId;joy.on=true;joyMove(e)});addEventListener('pointermove',e=>{if(e.pointerId===activeTouch)joyMove(e)});addEventListener('pointerup',e=>{if(e.pointerId===activeTouch){activeTouch=null;joy.on=false;joy.x=joy.y=0;$('joy').querySelector('i').style.transform='translate(0,0)'}});function joyMove(e){const r=$('joy').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=48,l=Math.hypot(dx,dy)||1,k=Math.min(1,max/l);joy.x=dx/l*k;joy.y=dy/l*k;$('joy').querySelector('i').style.transform=`translate(${dx/l*k*48}px,${dy/l*k*48}px)`} $('mInteract').onclick=interact;$('mRecipe').onclick=newOrder;
